[workspace]
members = [
     "crates/meta_bots",
    "crates/meta_common",
    "crates/meta_util",
    "crates/meta_tracing",
    "crates/meta_address",
    "crates/meta_contracts",
   
    "crates/meta_mev_service",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
proc-macro2 = "1"
syn = { version = "1", features = ["full"]}
quote = "1"
hex = "0.4"
rand = "0.8"
thiserror = "1.0"
once_cell = "1.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
dashmap = "5.4"
## async
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-tungstenite = { version = "0.17", features = ["native-tls"] }